import { StyleSheet } from "react-native";

const COLORS = {
  primary: "#3040b0",
  secondary: "#707888",
  accent: "#40a8ff",
  translucentWhite: 'rgba(255, 255, 255, 0.5)',
  white: "#fff",
  black: "#000",
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  square: {
    backgroundColor: '#f4f4f4',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    width: '100%',
    maxWidth: 400,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5, 
  },
  texto: {
    fontSize: 16,
    marginBottom: 10,
    color: '#333',
    fontWeight: 'bold',
  },
  textBox: {
    width: '80%',
    height: 45,
    borderColor: '#aaa',
    borderWidth: 1.5,
    borderRadius: 8,
    marginBottom: 20,
    paddingHorizontal: 12,
    fontSize: 16,
    backgroundColor: COLORS.white,
  },
  button: {
    backgroundColor: COLORS.accent, 
    paddingVertical: 15,
    paddingHorizontal: 50,
    borderRadius: 10,
    marginBottom: 20,
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5, 
  },
  buttonText: {
    color: COLORS.white,
    fontSize: 18,
    fontWeight: 'bold',
  },
  resultadoContainer: {
    marginTop: 20,
    padding: 15,
    borderRadius: 8,
    width: '80%',
    alignItems: 'center',
  },
  resultadoTexto: {
    fontSize: 20,
    color: COLORS.white,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  textTitle: {
    fontSize: 60,
    color: COLORS.accent,
    marginBottom: 50,
    fontWeight: '500',
  },
});
